---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates (ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    
- hosts: web_servers
  become: true
  tasks:
  
  - name: install  apache2 package (Ubuntu)
    tags: apache,apache2,ubuntu
    apt:
       name:
         - apache2
         - libapache2-mod-php
       state: latest

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
